name: Captcha
version: ${project.version}
description: Bots are now the past
main: me.kyllian.captcha.spigot.CaptchaPlugin
author: Kyllian
api-version: 1.13
softdepend: [AuthMe]

commands:
  captcha:
    usage: /<command>
    aliases:
      - cap
    description: Main command of the Captcha plugin
    permission: captcha.command