name: Captcha
version: 1.11
description: Bots are now the past
main: me.kyllian.captcha.CaptchaPlugin
api-version: 1.13
softdepend: [AuthMe]

commands:
  captcha:
    usage: /<command>
    aliases:
      - cap
    description: Main command of the Captcha p~lugin