name: Captcha
version: 1.04
description: Bots are now the past
main: me.kyllian.captcha.CaptchaPlugin
api-version: '1.13'
softdepend: [AuthMe]
author: Kyllian

commands:
  captcha:
    usage: /<command>
    description: Main command of the Captcha p~lugin